<% ci_opts = " -r features --color --tags ~@on_demand --tags ~@wip --tags ~@unstable --tags ~@manual --tags ~@pending --format junit -o results/junit/ --format Cucumber::Blinkbox::Formatter::Html -o features_report.html --format pretty"  %>

default: -p local_debug
local_debug: -r features --tags ~@wip environment=production debug=true --format pretty --color

ci-smoke-qa-debug:              <%= ci_opts %> --tags @smoke
ci-regression-qa-debug:         <%= ci_opts %>
ci-alltests-production-debug:   <%= ci_opts %> --tags ~@new_data
ci-smoke-production-debug:      <%= ci_opts %> --tags @smoke