<% ci_opts = " -r features --color --tags ~@on_demand --tags ~@wip --tags ~@unstable --tags ~@manual --tags ~@pending --format junit -o results/junit/ --format Cucumber::Blinkbox::Formatter::Html -o features_report.html --format pretty"  %>

#default: -p local_debug
#local_debug: -r features --tags ~@wip environment=production debug=true --format pretty --color

ci-smoke-dev-debug:             <%= ci_opts %> --tags @smoke,@new_data,@dev environment=dev-debug
ci-smoke-qa-debug:              <%= ci_opts %> --tags @smoke,@new_data,@qa environment=qa-debug
ci-smoke-production-debug:      <%= ci_opts %> --tags @smoke environment=production-debug

ci-sanity-dev-debug:            <%= ci_opts %> --tags @sanity,@smoke,@new_data,@dev environment=dev-debug
ci-sanity-qa-debug:             <%= ci_opts %> --tags @sanity,@smoke,@new_data,@qa environment=qa-debug
ci-sanity-production-debug:     <%= ci_opts %> --tags @sanity,@smoke environment=production-debug

ci-regression-dev-debug:        <%= ci_opts %> --tags ~@qa environment=dev-debug
ci-regression-qa-debug:         <%= ci_opts %> --tags ~@dev environment=qa-debug
ci-regression-production-debug: <%= ci_opts %> --tags ~@new_data,~@dev,~@qa environment=production-debug



