<% ci_opts = " -r features --color --tags ~@on_demand --tags ~@wip --tags ~@unstable --tags ~@manual --tags ~@pending --format Cucumber::Blinkbox::Formatter::Html -o features_report.html --format pretty"  %>

#default: -p local_debug
#local_debug: -r features --tags ~@wip environment=production debug=true --format pretty --color

ci-smoke-dev-debug:             <%= ci_opts %> --tags @smoke-all,@smoke-dev,@new_data environment=dev-debug
ci-smoke-qa-debug:              <%= ci_opts %> --tags @smoke-all,@smoke-qa,@new_data environment=qa-debug
ci-smoke-production-debug:      <%= ci_opts %> --tags @smoke-all environment=production-debug

ci-sanity-dev-debug:            <%= ci_opts %> --tags @sanity-all,@sanity-dev,@smoke-all,@smoke-dev,@new_data environment=dev-debug
ci-sanity-qa-debug:             <%= ci_opts %> --tags @sanity-all,@sanity-qa,@smoke-all,@smoke-qa,@new_data environment=qa-debug
ci-sanity-production-debug:     <%= ci_opts %> --tags @sanity-all,@smoke-all environment=production-debug

ci-regression-dev-debug:        <%= ci_opts %> --tags ~@qa,~@production,~@smoke-qa,~@sanity-qa environment=dev-debug
ci-regression-qa-debug:         <%= ci_opts %> --tags ~@dev,~@production,~@smoke-dev,~@sanity-dev environment=qa-debug
ci-regression-production-debug: <%= ci_opts %> --tags ~@new_data,~@dev,~@qa,~@sanity-dev,~@smoke-dev,~@smoke-qa,~@sanity-qa environment=production-debug



