anon:
 toggle_menu: "* id:'togglebutton_home'"
 toggle_menu_signin: "TextView marked:'Sign in'"
login:
 el_tryout: "* marked:'Try it out'"
 el_signin: "* marked:'Sign in to find books and more'"
 el_signedin: "BBBTextView marked:'Your library'"
reader:
 el_touch_cover: "BookCover index:0"
 el_touch_bookmark: "ImageView marked:'Reader bookmark'"
 el_bookmark: "* id:'imageview_bookmark'"
