#BUILD AND INSTALLATION
remote:
 endpoint_download: http://mobile-build.mobcastdev.local:8080/jenkins/job/BBB%20Android%20App/lastSuccessfulBuild/artifact/app/build/apk/*zip*/apk.zip   
 endpoint_payload: apk.zip
project:
 build_dir: build
 log_path: logs
 log_file: log.log
 log_rotation: daily
