new_user:
  editext_emailaddress:
    calabash_test@gmail.com
  editext_firstname:
    John
  editext_lastname:
    Doe
  editext_password:
    password
  editext_reenterpassword:
    password

existing_user:
  username:
    calabash_test@gmail.com
  password:
    password

url:
  auth:
    https://auth.blinkboxbooks.com

qa:
  host:
    https://api.blinkboxbooks.com/service

auth_user:
  grant_type:
    password
  username:
    calabash_test@gmail.com
  password:
    password

samples_books:
  - 9781451685336
  - 9780062210272
  - 9781135818944
  - 9781136254017
  - 9781135015541
